### ISSUE TITLE
channel view => channel filter is case sensitive

### ISSUE THREAD

**Issue by KraXen72** [probablykasper/kadium#10]
please make it case insensitive. it really does not make sense for it to be case sensitive. i do not remember the capitalization for 50+ channels.
thanks.

**Comment by probablykasper** [comment]
Would definitely like that for the Videos page. Maybe that should be done using [tantivy](https://github.com/quickwit-oss/tantivy), though that would mean basically having two databases

For the channels page, it would be easier to do

**Comment by KraXen72** [comment]
thanks!!

**Comment by probablykasper** [comment]
Just released it as part ot v1.6.0
