### ISSUE TITLE
youtube.com/user url's don't work

### ISSUE THREAD

**Issue by KraXen72** [probablykasper/kadium#5]
some channels have a channel/ url by default from the https://www.youtube.com/feed/channels page, some use a /user which does not work.

**Comment by probablykasper** [comment]
Duplicate of https://github.com/probablykasper/kadium/issues/3

**Comment by probablykasper** [comment]
All channel URLs should work now. Including `/lacunarecs`, `/@lacunarecs`, `/c/lacunarecs`, `/user/lacunarecs` and even ones like `/lacunarecs/playlists` etc
